# Generated by Django 3.2.3 on 2021-07-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='add_flight',
        ),
    ]
