# Generated by Django 3.2.5 on 2021-07-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210717_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='classes',
            field=models.CharField(choices=[('economey', 'economey'), ('first', 'first')], default='economey', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=0, default=600, max_digits=5),
        ),
    ]
